//$file${../../Inc::shared.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Audioplayer.qm
// File:  ${../../Inc::shared.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../Inc::shared.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef Shared_H_
#define Shared_H_

#include "qpc.h"
#include "bsp.h"

//$declare${Shared::AudioPlayerSignals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AudioPlayerSignals} ..............................................
enum AudioPlayerSignals {
    TIMEOUT_SIG = Q_USER_SIG,
    PLUS_SIG,
    MINUS_SIG,
    NEXT_SIG,
    PREV_SIG,
    DONE_SIG,
    MODE_SIG,
    PLAYPAUSE_SIG,
    RELEASE_SIG,
    TERMINATE_SIG,
    MAX_SIG,

};
//$enddecl${Shared::AudioPlayerSignals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${Shared::AO_AudioPlayer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_AudioPlayer} ..................................................
extern QActive * const AO_AudioPlayer;
//$enddecl${Shared::AO_AudioPlayer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${Shared::PLAYER_QUEUE} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::PLAYER_QUEUE} ....................................................
#define PLAYER_QUEUE 10U
//$enddecl${Shared::PLAYER_QUEUE} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${Shared::appConstants} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::appConstants} ....................................................
enum appConstants  {
    PLUS,
    MINUS,
    VOL_INTERVAL = BSP_TICKS_PER_SEC,
};
//$enddecl${Shared::appConstants} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


#endif
