//$file${.::audioPlayer.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Audioplayer.qm
// File:  ${.::audioPlayer.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::audioPlayer.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "AudioPlayer.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AudioPlayer} ........................................................

//${AOs::AudioPlayer::SM} ....................................................
QState AudioPlayer_initial(AudioPlayer * const me, void const * const par) {
    //${AOs::AudioPlayer::SM::initial}
    me->vol = 3U;
    me->volChanged = 0U;

    QS_FUN_DICTIONARY(&AudioPlayer_MODE);
    QS_FUN_DICTIONARY(&AudioPlayer_Radio);
    QS_FUN_DICTIONARY(&AudioPlayer_Bluetooth);
    QS_FUN_DICTIONARY(&AudioPlayer_BT_Init);
    QS_FUN_DICTIONARY(&AudioPlayer_Pairing);
    QS_FUN_DICTIONARY(&AudioPlayer_Pair);
    QS_FUN_DICTIONARY(&AudioPlayer_SD_card_Input);
    QS_FUN_DICTIONARY(&AudioPlayer_OFF);

    return Q_TRAN(&AudioPlayer_MODE);
}

//${AOs::AudioPlayer::SM::MODE} ..............................................
QState AudioPlayer_MODE(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::MODE::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&AudioPlayer_Radio);
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::PLUS}
        case PLUS_SIG: {
            QTimeEvt_armX(&me->volTimerEvt, VOL_INTERVAL, VOL_INTERVAL);
            me->sign = (uint8_t)PLUS;

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::TIMEOUT}
        case TIMEOUT_SIG: {
            me->volChanged = 1U;
            //${AOs::AudioPlayer::SM::MODE::TIMEOUT::[me->sign==(uint8_t)PLUS]}
            if (me->sign == (uint8_t)PLUS) {
                me->vol++;

                status_ = Q_HANDLED();
            }
            //${AOs::AudioPlayer::SM::MODE::TIMEOUT::[else]}
            else {
                me->vol--;
                status_ = Q_HANDLED();
            }
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::MINUS}
        case MINUS_SIG: {
            QTimeEvt_armX(&me->volTimerEvt, VOL_INTERVAL, VOL_INTERVAL);
            me->sign = (uint8_t)MINUS;

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::RELEASE}
        case RELEASE_SIG: {
            QTimeEvt_disarm(&me->volTimerEvt);
            //${AOs::AudioPlayer::SM::MODE::RELEASE::[!me->volChanged]}
            if (!me->volChanged) {
                //${AOs::AudioPlayer::SM::MODE::RELEASE::[!me->volChanged~::[me->sign==(uint8_t)PLUS]}
                if (me->sign == (uint8_t)PLUS) {
                    static const QEvt nextEvt = QEVT_INITIALIZER(NEXT_SIG);
                    QACTIVE_POST(AO_AudioPlayer, &nextEvt, (void)0U);
                    status_ = Q_HANDLED();
                }
                //${AOs::AudioPlayer::SM::MODE::RELEASE::[!me->volChanged~::[else]}
                else {
                    static const QEvt prevEvt = QEVT_INITIALIZER(PREV_SIG);
                    QACTIVE_POST(AO_AudioPlayer, &prevEvt, (void)0U);
                    status_ = Q_HANDLED();
                }
            }
            //${AOs::AudioPlayer::SM::MODE::RELEASE::[else]}
            else {
                me->volChanged = 0U;
                status_ = Q_HANDLED();
            }
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::TERMINATE}
        case TERMINATE_SIG: {
            status_ = Q_TRAN(&AudioPlayer_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::MODE::Radio} .......................................
QState AudioPlayer_Radio(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::MODE::Radio}
        case Q_ENTRY_SIG: {
            //Power the anttena
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Radio}
        case Q_EXIT_SIG: {
            //Disconnect the Antenna
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Radio::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&AudioPlayer_Bluetooth);
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Radio::PLAYPAUSE}
        case PLAYPAUSE_SIG: {
            //Mute the speckers
            bspMute();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Radio::NEXT}
        case NEXT_SIG: {
            //Play next radio Satation
            BspSeekNext();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Radio::PREV}
        case PREV_SIG: {
            //play previous station
            BspSeekPrev();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&AudioPlayer_MODE);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::MODE::Bluetooth} ...................................
QState AudioPlayer_Bluetooth(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::MODE::Bluetooth}
        case Q_EXIT_SIG: {
            //DIs able the BT Module and
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&AudioPlayer_BT_Init);
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&AudioPlayer_SD_card_Input);
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::PLAYPAUSE}
        case PLAYPAUSE_SIG: {
            //transmit the paly play sinal command to the Master
            BspTramitSignal();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::NEXT}
        case NEXT_SIG: {
            //transmit the next signal command to master
            bspTrasNext();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::PREV}
        case PREV_SIG: {
            //transmit the previous signal command to master
            bspTrasPrev();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&AudioPlayer_MODE);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::MODE::Bluetooth::BT_Init} ..........................
QState AudioPlayer_BT_Init(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::BT_Init}
        case Q_ENTRY_SIG: {
            //Power BT Module and set the device in slave mode
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::BT_Init::DONE}
        case DONE_SIG: {
            status_ = Q_TRAN(&AudioPlayer_Pairing);
            break;
        }
        default: {
            status_ = Q_SUPER(&AudioPlayer_Bluetooth);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::MODE::Bluetooth::Pairing} ..........................
QState AudioPlayer_Pairing(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::MODE::Bluetooth::Pairing::DONE}
        case DONE_SIG: {
            status_ = Q_TRAN(&AudioPlayer_Pair);
            break;
        }
        default: {
            status_ = Q_SUPER(&AudioPlayer_Bluetooth);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::MODE::Bluetooth::Pair} .............................
QState AudioPlayer_Pair(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&AudioPlayer_Bluetooth);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::MODE::SD_card_Input} ...............................
QState AudioPlayer_SD_card_Input(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::MODE::SD_card_Input}
        case Q_ENTRY_SIG: {
            //mount card and resume play
            bspMountSDCard();
            bspResumeRead();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::SD_card_Input}
        case Q_EXIT_SIG: {
            //save current play context and unmount card
            bspSaveReadState();
            bspUnmountSDCard();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::SD_card_Input::MODE}
        case MODE_SIG: {
            status_ = Q_TRAN(&AudioPlayer_Radio);
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::SD_card_Input::PLAYPAUSE}
        case PLAYPAUSE_SIG: {
            //pause current read and play operation
            bspPauseRead();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::SD_card_Input::NEXT}
        case NEXT_SIG: {
            //Read Next mp3file from card.
            bspReadNext();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::AudioPlayer::SM::MODE::SD_card_Input::PREV}
        case PREV_SIG: {
            //Read Previos mp3file from card.
            bspReadPrev();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&AudioPlayer_MODE);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer::SM::OFF} ...............................................
QState AudioPlayer_OFF(AudioPlayer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::AudioPlayer::SM::OFF}
        case Q_ENTRY_SIG: {
            BSP_terminate();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::AudioPlayer_inst} ...................................................
static AudioPlayer AudioPlayer_inst;
//$enddef${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::AudioPlayer_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AudioPlayer_ctor} ................................................
void AudioPlayer_ctor(void) {
    AudioPlayer * const me = &AudioPlayer_inst;

    me->vol = (uint8_t)3U;

    QActive_ctor(&me->super, Q_STATE_CAST(&AudioPlayer_initial));

    QTimeEvt_ctorX(&me->volTimerEvt, &me->super, TIMEOUT_SIG, 0U);

    QTimeEvt_ctorX(&me->volTimerEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${Shared::AudioPlayer_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::AO_AudioPlayer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_AudioPlayer} ..................................................
QActive * const AO_AudioPlayer = &AudioPlayer_inst.super;
//$enddef${Shared::AO_AudioPlayer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

